<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>15.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DeviceSpecificBuild>True</DeviceSpecificBuild>
    <RuntimeIdentifier>iossimulator-arm64</RuntimeIdentifier>
    <MTouchLink>None</MTouchLink>
    <ForceSimulatorX64ArchitectureInIDE>false</ForceSimulatorX64ArchitectureInIDE>
    <CodesignRequireProvisioningProfile>true</CodesignRequireProvisioningProfile>
    <DisableCodesignVerification>true</DisableCodesignVerification>
    <CodesignKey>iPhone Developer</CodesignKey>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MvvmCross" Version="10.1.2" />
    <PackageReference Include="RevenueCat.DotNet.Bindings" Version="5.78.0-rc1" />
    <PackageReference Include="RevenueCatUI.DotNet.Bindings" Version="5.78.0-rc1" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Xamarin" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sample.Core\Sample.Core.csproj" />
  </ItemGroup>
</Project>
