#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef REVENUECATUI_SWIFT_H
#define REVENUECATUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RevenueCatUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RevenueCatUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol RCCustomerCenterViewControllerDelegate;
@class NSCoder;
@class NSString;
@class NSBundle;
/// Use the Customer Center in your app to help your customers manage common support tasks.
/// Customer Center is a self-service UI that can be added to your app to help
/// your customers manage their subscriptions on their own. With it, you can prevent
/// churn with pre-emptive promotional offers, capture actionable customer data with
/// exit feedback prompts, and lower support volumes for common inquiries — all
/// without any help from your support team.
/// The <code>CustomerCenterViewController</code> can be used to integrate the Customer Center directly in your app with UIKit.
/// For more information, see the <a href="https://www.revenuecat.com/docs/tools/customer-center">Customer Center docs</a>.
SWIFT_CLASS_NAMED("CustomerCenterViewController") SWIFT_AVAILABILITY(watchos,unavailable) SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(macos,unavailable) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCCustomerCenterViewController : UIViewController
/// Create a view controller with a delegate for receiving callbacks.
/// This initializer is designed for Objective-C compatibility.
/// Swift users may prefer using the closure-based initializer instead.
/// \param delegate The delegate to receive Customer Center callbacks.
///
- (nonnull instancetype)initWithDelegate:(id <RCCustomerCenterViewControllerDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class RCCustomerInfo;
@class NSError;
SWIFT_ENUM_FWD_DECL(NSInteger, RCRefundRequestStatus)
@class RCStoreTransaction;
/// Delegate protocol for <code>CustomerCenterViewController</code>.
/// Use this delegate for Objective-C compatibility. Swift users can alternatively use the
/// closure-based initializer.
SWIFT_PROTOCOL_NAMED("CustomerCenterViewControllerDelegate") SWIFT_AVAILABILITY(watchos,unavailable) SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(macos,unavailable) SWIFT_AVAILABILITY(ios,introduced=15.0)
@protocol RCCustomerCenterViewControllerDelegate <NSObject>
@optional
/// Called when a restore operation starts.
- (void)customerCenterViewControllerDidStartRestore:(RCCustomerCenterViewController * _Nonnull)controller;
/// Called when a restore operation is about to start.
/// The <code>resume</code> closure must be called with <code>true</code> to proceed or <code>false</code> to cancel.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didInitiateRestoreWithResume:(void (^ _Nonnull)(BOOL))resume;
/// Called when a restore operation completes successfully.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didFinishRestoringWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo;
/// Called when a restore operation fails.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didFailRestoringWithError:(NSError * _Nonnull)error;
/// Called when the user navigates to the manage subscriptions screen.
- (void)customerCenterViewControllerDidShowManageSubscriptions:(RCCustomerCenterViewController * _Nonnull)controller;
/// Called when a refund request starts.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didStartRefundRequestForProductId:(NSString * _Nonnull)productId;
/// Called when a refund request completes.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didCompleteRefundRequestForProductId:(NSString * _Nonnull)productId withStatus:(enum RCRefundRequestStatus)status;
/// Called when a feedback survey is completed.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didCompleteFeedbackSurveyWithOptionId:(NSString * _Nonnull)optionId;
/// Called when change plans is selected.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didSelectChangePlansWithOptionId:(NSString * _Nonnull)optionId;
/// Called when a custom action is selected.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didSelectCustomActionWithIdentifier:(NSString * _Nonnull)actionIdentifier purchaseIdentifier:(NSString * _Nullable)purchaseIdentifier;
/// Called when a promotional offer succeeds.
/// note:
/// Prefer <code>customerCenterViewController(_:didSucceedWithPromotionalOffer:customerInfo:transaction:)</code>
/// which also provides purchase details. If both methods are implemented, both will be called
/// on a successful promotional offer purchase.
- (void)customerCenterViewControllerDidSucceedWithPromotionalOffer:(RCCustomerCenterViewController * _Nonnull)controller;
/// Called when a promotional offer purchase completes successfully,
/// providing the resulting customer info, transaction, and the promotional offer identifier.
/// note:
/// If the delegate also implements
/// <code>customerCenterViewControllerDidSucceedWithPromotionalOffer(_:)</code>,
/// both methods will be called.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didSucceedWithPromotionalOffer:(NSString * _Nonnull)offerId customerInfo:(RCCustomerInfo * _Nonnull)customerInfo transaction:(RCStoreTransaction * _Nonnull)transaction;
/// Called when the Customer Center is dismissed.
/// Make sure to call dismiss(animated: ) on the CustomerCenterViewController to actually dismiss
/// the Customer Center.
- (void)customerCenterViewControllerWasDismissed:(RCCustomerCenterViewController * _Nonnull)controller;
@end

@protocol RCPaywallViewControllerDelegate;
@class RCOffering;
@protocol RCPaywallPurchaseHandler;
@class RCPresentedOfferingContext;
@class UITouch;
@class UIEvent;
/// A view controller for displaying the paywall for an <code>Offering</code>.
/// <h2>Exit Offer Support</h2>
/// This view controller sets itself as the <code>presentationController?.delegate</code> to intercept
/// swipe-to-dismiss gestures for exit offer support. When an exit offer is available and the user
/// attempts to dismiss without purchasing, the exit offer paywall will be presented instead.
/// Exit offers take priority over any existing presentation controller delegate. If you have an
/// existing delegate, it will be preserved and delegate methods will be forwarded to it only when
/// exit offers are not being handled.
/// important:
/// If you need to set a custom <code>presentationController?.delegate</code> in a subclass,
/// do so <em>before</em> calling <code>super.viewWillAppear(_:)</code>. This ensures your delegate is captured
/// and forwarded. Setting it afterwards will override the exit offer handling, potentially
/// breaking exit offer support.
/// seealso:
/// <code>PaywallView</code> for <code>SwiftUI</code>.
SWIFT_CLASS_NAMED("PaywallViewController") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCPaywallViewController : UIViewController
/// See <code>PaywallViewControllerDelegate</code> for receiving purchase events.
@property (nonatomic, weak) id <RCPaywallViewControllerDelegate> _Nullable delegate;
/// Sets a string custom variable value for the given key.
/// \param value The string value to set.
///
/// \param key The variable key (without the <code>custom.</code> prefix).
///
- (void)setCustomVariable:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
/// Sets a numeric custom variable value for the given key.
/// \param value The numeric value to set.
///
/// \param key The variable key (without the <code>custom.</code> prefix).
///
- (void)setCustomVariableNumber:(double)value forKey:(NSString * _Nonnull)key;
/// Sets a boolean custom variable value for the given key.
/// \param value The boolean value to set.
///
/// \param key The variable key (without the <code>custom.</code> prefix).
///
- (void)setCustomVariableBool:(BOOL)value forKey:(NSString * _Nonnull)key;
/// Initialize a <code>PaywallViewController</code> with an optional <code>Offering</code>.
/// \param offering The <code>Offering</code> containing the desired paywall to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param displayCloseButton Set this to <code>true</code> to automatically include a close button.
///
/// \param shouldBlockTouchEvents Whether to interecept all touch events propagated through this VC
///
/// \param dismissRequestedHandler If this is not set, the paywall will close itself automatically
/// after a successful purchase. Otherwise use this handler to handle dismissals of the paywall
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering displayCloseButton:(BOOL)displayCloseButton shouldBlockTouchEvents:(BOOL)shouldBlockTouchEvents dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler;
/// Objective-C compatible initializer that accepts a <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic.
/// \param offering The <code>Offering</code> containing the desired paywall to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param displayCloseButton Set this to <code>true</code> to automatically include a close button.
///
/// \param shouldBlockTouchEvents Whether to intercept all touch events propagated through this VC.
///
/// \param purchaseHandler An object implementing <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic. Only used when <code>Purchases</code> has been configured with
/// <code>.with(purchasesAreCompletedBy: .myApp)</code>.
///
/// \param dismissRequestedHandler If this is not set, the paywall will close itself automatically
/// after a successful purchase. Otherwise use this handler to handle dismissals of the paywall.
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering displayCloseButton:(BOOL)displayCloseButton shouldBlockTouchEvents:(BOOL)shouldBlockTouchEvents purchaseHandler:(id <RCPaywallPurchaseHandler> _Nullable)purchaseHandler dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
/// warning:
/// For internal use only
- (void)updateWithOffering:(RCOffering * _Nonnull)offering;
/// warning:
/// For internal use only
- (void)updateWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier SWIFT_DEPRECATED_MSG("use init with Offering instead");
/// warning:
/// For internal use only
- (void)updateWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier presentedOfferingContext:(RCPresentedOfferingContext * _Nullable)presentedOfferingContext;
/// warning:
/// For internal use only
- (void)updateWithDisplayCloseButton:(BOOL)displayCloseButton;
/// warning:
/// For internal use only
- (void)updateFontWithFontName:(NSString * _Nonnull)fontName;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// A view controller for displaying <code>PaywallData</code> for an <code>Offering</code> in a footer format.
/// This is used by the RevenueCat hybrid SDKs in order to get a View of the footer.
/// Consumers should normally use <code>PaywallViewController</code> instead.
/// seealso:
/// <code>PaywallView</code> for <code>SwiftUI</code>.
SWIFT_CLASS_NAMED("PaywallFooterViewController") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCPaywallFooterViewController : RCPaywallViewController
/// Objective-C compatible initializer that accepts a <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic.
/// important:
/// <code>purchaseHandler</code> is only used when <code>Purchases</code> has been configured with
/// <code>.with(purchasesAreCompletedBy: .myApp)</code>. Otherwise, the default purchase and restore
/// implementations are used and the handler is ignored.
/// \param offering The <code>Offering</code> containing the desired <code>PaywallData</code> to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param purchaseHandler An object implementing <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic.
///
/// \param dismissRequestedHandler If this is not set, the paywall footer will close itself
/// automatically after a successful purchase. Otherwise use this handler to handle dismissals
/// of the paywall.
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering purchaseHandler:(id <RCPaywallPurchaseHandler> _Nullable)purchaseHandler dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
/// Initialize a <code>PaywallFooterViewController</code> with an optional <code>Offering</code>.
/// \param offering The <code>Offering</code> containing the desired <code>PaywallData</code> to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param dismissRequestedHandler If this is not set, the paywall footer will close itself automatically
/// after a successful purchase. Otherwise use this handler to handle dismissals of the paywall.
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
/// Initialize a <code>PaywallFooterViewController</code> with an <code>Offering</code> identifier.
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use init with Offering instead");
/// Initialize a <code>PaywallFooterViewController</code> with an <code>offeringIdentifier</code> and <code>presentedOfferingContext</code>.
/// \param presentedOfferingContext the context in which this offer was presented
///
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier presentedOfferingContext:(RCPresentedOfferingContext * _Nullable)presentedOfferingContext dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
/// Initialize a <code>PaywallFooterViewController</code> with an <code>offeringIdentifier</code> and custom <code>fontName</code>.
/// \param fontName a custom font name for this paywall. See <code>CustomPaywallFontProvider</code>.
///
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier fontName:(NSString * _Nonnull)fontName dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use init with Offering instead");
/// Initialize a <code>PaywallFooterViewController</code> with an <code>offeringIdentifier</code>,
/// <code>presentedOfferingContext</code> and custom <code>fontName</code>.
/// \param presentedOfferingContext the context in which this offer was presented
///
/// \param fontName a custom font name for this paywall. See <code>CustomPaywallFontProvider</code>.
///
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier presentedOfferingContext:(RCPresentedOfferingContext * _Nullable)presentedOfferingContext fontName:(NSString * _Nonnull)fontName dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class RCPackage;
/// Objective-C compatible protocol for handling custom purchase and restore logic.
/// Implement this protocol to provide custom purchase and restore behavior when <code>Purchases</code>
/// has been configured with <code>.with(purchasesAreCompletedBy: .myApp)</code>.
/// Pass an instance to the <code>PaywallViewController</code> or <code>PaywallFooterViewController</code>
/// initializer via the <code>purchaseHandler</code> parameter.
SWIFT_PROTOCOL_NAMED("PaywallPurchaseHandler") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@protocol RCPaywallPurchaseHandler
/// Performs a purchase for the given package.
/// \param package The <code>Package</code> to purchase.
///
/// \param completion Must be called when the purchase completes.
/// <ul>
///   <li>
///     <code>userCancelled</code>: <code>true</code> if the user cancelled the purchase; otherwise, <code>false</code>.
///   </li>
///   <li>
///     <code>error</code>: An optional error that occurred during the purchase, or <code>nil</code> if none.
///   </li>
/// </ul>
///
- (void)performPurchaseFor:(RCPackage * _Nonnull)package completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
/// Performs a restore operation.
/// \param completion Must be called when the restore completes.
/// <ul>
///   <li>
///     <code>success</code>: <code>true</code> if the restore succeeded; otherwise, <code>false</code>.
///   </li>
///   <li>
///     <code>error</code>: An optional error that occurred during the restore, or <code>nil</code> if none.
///   </li>
/// </ul>
///
- (void)performRestoreWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end

@class UIPresentationController;
SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCPaywallViewController (SWIFT_EXTENSION(RevenueCatUI)) <UIAdaptivePresentationControllerDelegate>
- (BOOL)presentationControllerShouldDismiss:(UIPresentationController * _Nonnull)presentationController SWIFT_WARN_UNUSED_RESULT;
- (void)presentationControllerDidAttemptToDismiss:(UIPresentationController * _Nonnull)presentationController;
- (void)presentationControllerWillDismiss:(UIPresentationController * _Nonnull)presentationController;
- (void)presentationControllerDidDismiss:(UIPresentationController * _Nonnull)presentationController;
@end

/// Delegate for <code>PaywallViewController</code>.
SWIFT_PROTOCOL_NAMED("PaywallViewControllerDelegate") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@protocol RCPaywallViewControllerDelegate
@optional
/// Notifies that a purchase has started in a <code>PaywallViewController</code>.
- (void)paywallViewControllerDidStartPurchase:(RCPaywallViewController * _Nonnull)controller;
/// Notifies that a purchase has started in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didStartPurchaseWithPackage:(RCPackage * _Nonnull)package;
/// Notifies that a purchase has completed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFinishPurchasingWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo;
/// Notifies that a purchase has completed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFinishPurchasingWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo transaction:(RCStoreTransaction * _Nullable)transaction;
/// Notifies that a purchase has been cancelled in a <code>PaywallViewController</code>.
- (void)paywallViewControllerDidCancelPurchase:(RCPaywallViewController * _Nonnull)controller;
/// Notifies that the purchase operation has failed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFailPurchasingWithError:(NSError * _Nonnull)error;
/// Notifies that a restore has started in a <code>PaywallViewController</code>.
- (void)paywallViewControllerDidStartRestore:(RCPaywallViewController * _Nonnull)controller;
/// Notifies that the restore operation has completed in a <code>PaywallViewController</code>.
/// warning:
/// Receiving a <code>CustomerInfo</code>does not imply that the user has any entitlements,
/// simply that the process was successful. You must verify the <code>CustomerInfo/entitlements</code>
/// to confirm that they are active.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFinishRestoringWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo;
/// Notifies that the restore operation has failed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFailRestoringWithError:(NSError * _Nonnull)error;
/// Notifies that the <code>PaywallViewController</code> was dismissed.
- (void)paywallViewControllerWasDismissed:(RCPaywallViewController * _Nonnull)controller;
/// For internal use only.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didChangeSizeTo:(CGSize)size;
/// Notifies that an exit offer paywall is about to be presented.
/// note:
/// This is called after the original controller is dismissed and before the exit offer is presented.
/// Use this to associate the exit offer controller with the original controller for result tracking.
/// \param controller The original <code>PaywallViewController</code> that was dismissed.
///
/// \param exitOfferController The new <code>PaywallViewController</code> that will present the exit offer.
///
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller willPresentExitOfferController:(RCPaywallViewController * _Nonnull)exitOfferController;
/// Notifies that a purchase is about to be initiated, before the payment sheet is displayed.
/// This allows the delegate to gate the purchase flow (e.g., requiring authentication).
/// The <code>resume</code> closure <em>must</em> be called to either proceed (<code>true</code>) or cancel (<code>false</code>) the purchase.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didInitiatePurchaseWithPackage:(RCPackage * _Nonnull)package resume:(void (^ _Nonnull)(BOOL))resume;
/// Notifies that a restore is about to be initiated.
/// This allows the delegate to gate the restore flow (e.g., requiring authentication).
/// The <code>resume</code> closure <em>must</em> be called to either proceed (<code>true</code>) or cancel (<code>false</code>) the restore.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didInitiateRestoreWithResume:(void (^ _Nonnull)(BOOL))resume;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef REVENUECATUI_SWIFT_H
#define REVENUECATUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RevenueCatUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="RevenueCatUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@protocol RCCustomerCenterViewControllerDelegate;
@class NSCoder;
@class NSString;
@class NSBundle;
/// Use the Customer Center in your app to help your customers manage common support tasks.
/// Customer Center is a self-service UI that can be added to your app to help
/// your customers manage their subscriptions on their own. With it, you can prevent
/// churn with pre-emptive promotional offers, capture actionable customer data with
/// exit feedback prompts, and lower support volumes for common inquiries — all
/// without any help from your support team.
/// The <code>CustomerCenterViewController</code> can be used to integrate the Customer Center directly in your app with UIKit.
/// For more information, see the <a href="https://www.revenuecat.com/docs/tools/customer-center">Customer Center docs</a>.
SWIFT_CLASS_NAMED("CustomerCenterViewController") SWIFT_AVAILABILITY(watchos,unavailable) SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(macos,unavailable) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCCustomerCenterViewController : UIViewController
/// Create a view controller with a delegate for receiving callbacks.
/// This initializer is designed for Objective-C compatibility.
/// Swift users may prefer using the closure-based initializer instead.
/// \param delegate The delegate to receive Customer Center callbacks.
///
- (nonnull instancetype)initWithDelegate:(id <RCCustomerCenterViewControllerDelegate> _Nullable)delegate OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

@class RCCustomerInfo;
@class NSError;
SWIFT_ENUM_FWD_DECL(NSInteger, RCRefundRequestStatus)
@class RCStoreTransaction;
/// Delegate protocol for <code>CustomerCenterViewController</code>.
/// Use this delegate for Objective-C compatibility. Swift users can alternatively use the
/// closure-based initializer.
SWIFT_PROTOCOL_NAMED("CustomerCenterViewControllerDelegate") SWIFT_AVAILABILITY(watchos,unavailable) SWIFT_AVAILABILITY(tvos,unavailable) SWIFT_AVAILABILITY(macos,unavailable) SWIFT_AVAILABILITY(ios,introduced=15.0)
@protocol RCCustomerCenterViewControllerDelegate <NSObject>
@optional
/// Called when a restore operation starts.
- (void)customerCenterViewControllerDidStartRestore:(RCCustomerCenterViewController * _Nonnull)controller;
/// Called when a restore operation is about to start.
/// The <code>resume</code> closure must be called with <code>true</code> to proceed or <code>false</code> to cancel.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didInitiateRestoreWithResume:(void (^ _Nonnull)(BOOL))resume;
/// Called when a restore operation completes successfully.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didFinishRestoringWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo;
/// Called when a restore operation fails.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didFailRestoringWithError:(NSError * _Nonnull)error;
/// Called when the user navigates to the manage subscriptions screen.
- (void)customerCenterViewControllerDidShowManageSubscriptions:(RCCustomerCenterViewController * _Nonnull)controller;
/// Called when a refund request starts.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didStartRefundRequestForProductId:(NSString * _Nonnull)productId;
/// Called when a refund request completes.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didCompleteRefundRequestForProductId:(NSString * _Nonnull)productId withStatus:(enum RCRefundRequestStatus)status;
/// Called when a feedback survey is completed.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didCompleteFeedbackSurveyWithOptionId:(NSString * _Nonnull)optionId;
/// Called when change plans is selected.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didSelectChangePlansWithOptionId:(NSString * _Nonnull)optionId;
/// Called when a custom action is selected.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didSelectCustomActionWithIdentifier:(NSString * _Nonnull)actionIdentifier purchaseIdentifier:(NSString * _Nullable)purchaseIdentifier;
/// Called when a promotional offer succeeds.
/// note:
/// Prefer <code>customerCenterViewController(_:didSucceedWithPromotionalOffer:customerInfo:transaction:)</code>
/// which also provides purchase details. If both methods are implemented, both will be called
/// on a successful promotional offer purchase.
- (void)customerCenterViewControllerDidSucceedWithPromotionalOffer:(RCCustomerCenterViewController * _Nonnull)controller;
/// Called when a promotional offer purchase completes successfully,
/// providing the resulting customer info, transaction, and the promotional offer identifier.
/// note:
/// If the delegate also implements
/// <code>customerCenterViewControllerDidSucceedWithPromotionalOffer(_:)</code>,
/// both methods will be called.
- (void)customerCenterViewController:(RCCustomerCenterViewController * _Nonnull)controller didSucceedWithPromotionalOffer:(NSString * _Nonnull)offerId customerInfo:(RCCustomerInfo * _Nonnull)customerInfo transaction:(RCStoreTransaction * _Nonnull)transaction;
/// Called when the Customer Center is dismissed.
/// Make sure to call dismiss(animated: ) on the CustomerCenterViewController to actually dismiss
/// the Customer Center.
- (void)customerCenterViewControllerWasDismissed:(RCCustomerCenterViewController * _Nonnull)controller;
@end

@protocol RCPaywallViewControllerDelegate;
@class RCOffering;
@protocol RCPaywallPurchaseHandler;
@class RCPresentedOfferingContext;
@class UITouch;
@class UIEvent;
/// A view controller for displaying the paywall for an <code>Offering</code>.
/// <h2>Exit Offer Support</h2>
/// This view controller sets itself as the <code>presentationController?.delegate</code> to intercept
/// swipe-to-dismiss gestures for exit offer support. When an exit offer is available and the user
/// attempts to dismiss without purchasing, the exit offer paywall will be presented instead.
/// Exit offers take priority over any existing presentation controller delegate. If you have an
/// existing delegate, it will be preserved and delegate methods will be forwarded to it only when
/// exit offers are not being handled.
/// important:
/// If you need to set a custom <code>presentationController?.delegate</code> in a subclass,
/// do so <em>before</em> calling <code>super.viewWillAppear(_:)</code>. This ensures your delegate is captured
/// and forwarded. Setting it afterwards will override the exit offer handling, potentially
/// breaking exit offer support.
/// seealso:
/// <code>PaywallView</code> for <code>SwiftUI</code>.
SWIFT_CLASS_NAMED("PaywallViewController") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCPaywallViewController : UIViewController
/// See <code>PaywallViewControllerDelegate</code> for receiving purchase events.
@property (nonatomic, weak) id <RCPaywallViewControllerDelegate> _Nullable delegate;
/// Sets a string custom variable value for the given key.
/// \param value The string value to set.
///
/// \param key The variable key (without the <code>custom.</code> prefix).
///
- (void)setCustomVariable:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
/// Sets a numeric custom variable value for the given key.
/// \param value The numeric value to set.
///
/// \param key The variable key (without the <code>custom.</code> prefix).
///
- (void)setCustomVariableNumber:(double)value forKey:(NSString * _Nonnull)key;
/// Sets a boolean custom variable value for the given key.
/// \param value The boolean value to set.
///
/// \param key The variable key (without the <code>custom.</code> prefix).
///
- (void)setCustomVariableBool:(BOOL)value forKey:(NSString * _Nonnull)key;
/// Initialize a <code>PaywallViewController</code> with an optional <code>Offering</code>.
/// \param offering The <code>Offering</code> containing the desired paywall to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param displayCloseButton Set this to <code>true</code> to automatically include a close button.
///
/// \param shouldBlockTouchEvents Whether to interecept all touch events propagated through this VC
///
/// \param dismissRequestedHandler If this is not set, the paywall will close itself automatically
/// after a successful purchase. Otherwise use this handler to handle dismissals of the paywall
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering displayCloseButton:(BOOL)displayCloseButton shouldBlockTouchEvents:(BOOL)shouldBlockTouchEvents dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler;
/// Objective-C compatible initializer that accepts a <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic.
/// \param offering The <code>Offering</code> containing the desired paywall to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param displayCloseButton Set this to <code>true</code> to automatically include a close button.
///
/// \param shouldBlockTouchEvents Whether to intercept all touch events propagated through this VC.
///
/// \param purchaseHandler An object implementing <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic. Only used when <code>Purchases</code> has been configured with
/// <code>.with(purchasesAreCompletedBy: .myApp)</code>.
///
/// \param dismissRequestedHandler If this is not set, the paywall will close itself automatically
/// after a successful purchase. Otherwise use this handler to handle dismissals of the paywall.
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering displayCloseButton:(BOOL)displayCloseButton shouldBlockTouchEvents:(BOOL)shouldBlockTouchEvents purchaseHandler:(id <RCPaywallPurchaseHandler> _Nullable)purchaseHandler dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
/// warning:
/// For internal use only
- (void)updateWithOffering:(RCOffering * _Nonnull)offering;
/// warning:
/// For internal use only
- (void)updateWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier SWIFT_DEPRECATED_MSG("use init with Offering instead");
/// warning:
/// For internal use only
- (void)updateWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier presentedOfferingContext:(RCPresentedOfferingContext * _Nullable)presentedOfferingContext;
/// warning:
/// For internal use only
- (void)updateWithDisplayCloseButton:(BOOL)displayCloseButton;
/// warning:
/// For internal use only
- (void)updateFontWithFontName:(NSString * _Nonnull)fontName;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

/// A view controller for displaying <code>PaywallData</code> for an <code>Offering</code> in a footer format.
/// This is used by the RevenueCat hybrid SDKs in order to get a View of the footer.
/// Consumers should normally use <code>PaywallViewController</code> instead.
/// seealso:
/// <code>PaywallView</code> for <code>SwiftUI</code>.
SWIFT_CLASS_NAMED("PaywallFooterViewController") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCPaywallFooterViewController : RCPaywallViewController
/// Objective-C compatible initializer that accepts a <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic.
/// important:
/// <code>purchaseHandler</code> is only used when <code>Purchases</code> has been configured with
/// <code>.with(purchasesAreCompletedBy: .myApp)</code>. Otherwise, the default purchase and restore
/// implementations are used and the handler is ignored.
/// \param offering The <code>Offering</code> containing the desired <code>PaywallData</code> to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param purchaseHandler An object implementing <code>PaywallPurchaseHandler</code> for custom
/// purchase and restore logic.
///
/// \param dismissRequestedHandler If this is not set, the paywall footer will close itself
/// automatically after a successful purchase. Otherwise use this handler to handle dismissals
/// of the paywall.
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering purchaseHandler:(id <RCPaywallPurchaseHandler> _Nullable)purchaseHandler dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
/// Initialize a <code>PaywallFooterViewController</code> with an optional <code>Offering</code>.
/// \param offering The <code>Offering</code> containing the desired <code>PaywallData</code> to display.
/// <code>Offerings.current</code> will be used by default.
///
/// \param dismissRequestedHandler If this is not set, the paywall footer will close itself automatically
/// after a successful purchase. Otherwise use this handler to handle dismissals of the paywall.
///
- (nonnull instancetype)initWithOffering:(RCOffering * _Nullable)offering dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
/// Initialize a <code>PaywallFooterViewController</code> with an <code>Offering</code> identifier.
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use init with Offering instead");
/// Initialize a <code>PaywallFooterViewController</code> with an <code>offeringIdentifier</code> and <code>presentedOfferingContext</code>.
/// \param presentedOfferingContext the context in which this offer was presented
///
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier presentedOfferingContext:(RCPresentedOfferingContext * _Nullable)presentedOfferingContext dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
/// Initialize a <code>PaywallFooterViewController</code> with an <code>offeringIdentifier</code> and custom <code>fontName</code>.
/// \param fontName a custom font name for this paywall. See <code>CustomPaywallFontProvider</code>.
///
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier fontName:(NSString * _Nonnull)fontName dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_MSG("use init with Offering instead");
/// Initialize a <code>PaywallFooterViewController</code> with an <code>offeringIdentifier</code>,
/// <code>presentedOfferingContext</code> and custom <code>fontName</code>.
/// \param presentedOfferingContext the context in which this offer was presented
///
/// \param fontName a custom font name for this paywall. See <code>CustomPaywallFontProvider</code>.
///
- (nonnull instancetype)initWithOfferingIdentifier:(NSString * _Nonnull)offeringIdentifier presentedOfferingContext:(RCPresentedOfferingContext * _Nullable)presentedOfferingContext fontName:(NSString * _Nonnull)fontName dismissRequestedHandler:(void (^ _Nullable)(RCPaywallViewController * _Nonnull))dismissRequestedHandler OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class RCPackage;
/// Objective-C compatible protocol for handling custom purchase and restore logic.
/// Implement this protocol to provide custom purchase and restore behavior when <code>Purchases</code>
/// has been configured with <code>.with(purchasesAreCompletedBy: .myApp)</code>.
/// Pass an instance to the <code>PaywallViewController</code> or <code>PaywallFooterViewController</code>
/// initializer via the <code>purchaseHandler</code> parameter.
SWIFT_PROTOCOL_NAMED("PaywallPurchaseHandler") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@protocol RCPaywallPurchaseHandler
/// Performs a purchase for the given package.
/// \param package The <code>Package</code> to purchase.
///
/// \param completion Must be called when the purchase completes.
/// <ul>
///   <li>
///     <code>userCancelled</code>: <code>true</code> if the user cancelled the purchase; otherwise, <code>false</code>.
///   </li>
///   <li>
///     <code>error</code>: An optional error that occurred during the purchase, or <code>nil</code> if none.
///   </li>
/// </ul>
///
- (void)performPurchaseFor:(RCPackage * _Nonnull)package completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
/// Performs a restore operation.
/// \param completion Must be called when the restore completes.
/// <ul>
///   <li>
///     <code>success</code>: <code>true</code> if the restore succeeded; otherwise, <code>false</code>.
///   </li>
///   <li>
///     <code>error</code>: An optional error that occurred during the restore, or <code>nil</code> if none.
///   </li>
/// </ul>
///
- (void)performRestoreWithCompletion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
@end

@class UIPresentationController;
SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@interface RCPaywallViewController (SWIFT_EXTENSION(RevenueCatUI)) <UIAdaptivePresentationControllerDelegate>
- (BOOL)presentationControllerShouldDismiss:(UIPresentationController * _Nonnull)presentationController SWIFT_WARN_UNUSED_RESULT;
- (void)presentationControllerDidAttemptToDismiss:(UIPresentationController * _Nonnull)presentationController;
- (void)presentationControllerWillDismiss:(UIPresentationController * _Nonnull)presentationController;
- (void)presentationControllerDidDismiss:(UIPresentationController * _Nonnull)presentationController;
@end

/// Delegate for <code>PaywallViewController</code>.
SWIFT_PROTOCOL_NAMED("PaywallViewControllerDelegate") SWIFT_AVAILABILITY(tvos,introduced=15.0) SWIFT_AVAILABILITY(macos,introduced=12.0) SWIFT_AVAILABILITY(ios,introduced=15.0)
@protocol RCPaywallViewControllerDelegate
@optional
/// Notifies that a purchase has started in a <code>PaywallViewController</code>.
- (void)paywallViewControllerDidStartPurchase:(RCPaywallViewController * _Nonnull)controller;
/// Notifies that a purchase has started in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didStartPurchaseWithPackage:(RCPackage * _Nonnull)package;
/// Notifies that a purchase has completed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFinishPurchasingWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo;
/// Notifies that a purchase has completed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFinishPurchasingWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo transaction:(RCStoreTransaction * _Nullable)transaction;
/// Notifies that a purchase has been cancelled in a <code>PaywallViewController</code>.
- (void)paywallViewControllerDidCancelPurchase:(RCPaywallViewController * _Nonnull)controller;
/// Notifies that the purchase operation has failed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFailPurchasingWithError:(NSError * _Nonnull)error;
/// Notifies that a restore has started in a <code>PaywallViewController</code>.
- (void)paywallViewControllerDidStartRestore:(RCPaywallViewController * _Nonnull)controller;
/// Notifies that the restore operation has completed in a <code>PaywallViewController</code>.
/// warning:
/// Receiving a <code>CustomerInfo</code>does not imply that the user has any entitlements,
/// simply that the process was successful. You must verify the <code>CustomerInfo/entitlements</code>
/// to confirm that they are active.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFinishRestoringWithCustomerInfo:(RCCustomerInfo * _Nonnull)customerInfo;
/// Notifies that the restore operation has failed in a <code>PaywallViewController</code>.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didFailRestoringWithError:(NSError * _Nonnull)error;
/// Notifies that the <code>PaywallViewController</code> was dismissed.
- (void)paywallViewControllerWasDismissed:(RCPaywallViewController * _Nonnull)controller;
/// For internal use only.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didChangeSizeTo:(CGSize)size;
/// Notifies that an exit offer paywall is about to be presented.
/// note:
/// This is called after the original controller is dismissed and before the exit offer is presented.
/// Use this to associate the exit offer controller with the original controller for result tracking.
/// \param controller The original <code>PaywallViewController</code> that was dismissed.
///
/// \param exitOfferController The new <code>PaywallViewController</code> that will present the exit offer.
///
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller willPresentExitOfferController:(RCPaywallViewController * _Nonnull)exitOfferController;
/// Notifies that a purchase is about to be initiated, before the payment sheet is displayed.
/// This allows the delegate to gate the purchase flow (e.g., requiring authentication).
/// The <code>resume</code> closure <em>must</em> be called to either proceed (<code>true</code>) or cancel (<code>false</code>) the purchase.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didInitiatePurchaseWithPackage:(RCPackage * _Nonnull)package resume:(void (^ _Nonnull)(BOOL))resume;
/// Notifies that a restore is about to be initiated.
/// This allows the delegate to gate the restore flow (e.g., requiring authentication).
/// The <code>resume</code> closure <em>must</em> be called to either proceed (<code>true</code>) or cancel (<code>false</code>) the restore.
- (void)paywallViewController:(RCPaywallViewController * _Nonnull)controller didInitiateRestoreWithResume:(void (^ _Nonnull)(BOOL))resume;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
